/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user with nickname and credentials. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Registration result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            token?: string;
                            user?: components["schemas"]["User"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register/check-nickname": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check nickname availability. */
        get: {
            parameters: {
                query: {
                    nickname: components["parameters"]["NicknameQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start an email verification registration flow. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterStartRequest"];
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete registration with verification code. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterVerifyRequest"];
                };
            };
            responses: {
                200: components["responses"]["AuthResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with account credentials. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                200: components["responses"]["AuthResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the browser page-access session cookie. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login/captcha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a login captcha when required. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nickname?: string;
                        /** Format: email */
                        email?: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password for the authenticated user. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PasswordChangeRequest"];
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/password/reset/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start password reset flow. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/password/reset/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete password reset with verification code. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        code: string;
                        password: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Legacy alias for the authenticated user profile.
         * @deprecated
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["UserResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user profile. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["UserResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me/nickname": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update the authenticated user's nickname. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nickname: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["UserResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/nickname": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Legacy alias for updating the authenticated user's nickname.
         * @deprecated
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nickname: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["UserResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a public user profile. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: components["parameters"]["UserIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["UserResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{userId}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user records. */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["PageQuery"];
                    limit?: components["parameters"]["LimitQuery"];
                    mode?: string;
                    sort_by?: "time" | "score" | "board_sum";
                    order?: "asc" | "desc";
                    visibility?: "active" | "deleted" | "all";
                };
                header?: never;
                path: {
                    userId: components["parameters"]["UserIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User records. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            records?: components["schemas"]["GameRecord"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{userId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read aggregate user record statistics. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: components["parameters"]["UserIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User record statistics. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            data?: components["schemas"]["UserRecordStats"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read leaderboard rows. */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["LimitQuery"];
                    page?: components["parameters"]["PageQuery"];
                    period?: "all" | "daily" | "weekly" | "monthly";
                    mode?: string;
                    mode_key?: string;
                    metric?: "score" | "speed";
                    target_tile?: 2048 | 4096 | 8192 | 16384 | 32768;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Leaderboard result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            /** @enum {string} */
                            metric?: "score" | "speed";
                            target_tile?: number;
                            data?: components["schemas"]["LeaderboardEntry"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard/standard-4x4-no-undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the isolated standard 4x4 no-undo showcase leaderboard. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Standard 4x4 no-undo showcase result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            /** @constant */
                            mode_key: "standard_4x4_pow2_no_undo";
                            summary: components["schemas"]["LeaderboardShowcaseSummary"];
                            trend: components["schemas"]["LeaderboardShowcaseTrendPoint"][];
                            achievement_focus?: components["schemas"]["LeaderboardAchievementFocus"];
                            data: components["schemas"]["LeaderboardShowcaseEntry"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Legacy score submission endpoint.
         * @deprecated
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ScoreSubmitRequest"];
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a completed game record. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GameRecordSubmitRequest"];
                };
            };
            responses: {
                /** @description Record submission result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            record?: components["schemas"]["GameRecord"];
                            achievements?: components["schemas"]["UserAchievement"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{recordId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Soft-delete a record owned by the authenticated user. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    recordId: components["parameters"]["RecordIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{recordId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a soft-deleted record. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    recordId: components["parameters"]["RecordIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records/{recordId}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get or download a record replay. */
        get: {
            parameters: {
                query?: {
                    download?: "signed_url";
                };
                header?: never;
                path: {
                    recordId: components["parameters"]["RecordIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Replay payload or signed URL. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            replay?: string;
                            signed_url?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/replay/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read replay API capability metadata. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ranked-session/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a ranked session seed and token. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RankedSessionStartRequest"];
                };
            };
            responses: {
                /** @description Ranked session. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            data?: components["schemas"]["RankedSession"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ranked-session/attempt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a verified ranked-session begin or abandon event. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RankedSessionAttemptRequest"];
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
                /** @description Invalid attempt payload or replay. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Session is already terminal and cannot be abandoned. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ranked-checkpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the authenticated user's ranked checkpoint for a mode. */
        get: {
            parameters: {
                query: {
                    mode_key: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ranked checkpoint. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            data?: components["schemas"]["RankedCheckpoint"];
                        };
                    };
                };
            };
        };
        /** Persist ranked checkpoint state. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RankedCheckpoint"];
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        post?: never;
        /** Clear ranked checkpoint state for a mode. */
        delete: {
            parameters: {
                query: {
                    mode_key: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relay/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List relay cases for relay mode clients. */
        get: {
            parameters: {
                query?: {
                    board?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Relay case list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            data?: components["schemas"]["RelayCase"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relay/cases/{caseId}/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the latest relay case board snapshot. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    caseId: components["parameters"]["RelayCaseIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Relay case snapshot. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            data?: components["schemas"]["RelayCase"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relay/cases/{caseId}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the replay payload for a relay case. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    caseId: components["parameters"]["RelayCaseIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Relay case replay payload. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            replay?: string;
                            replay_string?: string;
                            data?: {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relay/cases/{caseId}/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or initialize a relay case shell. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    caseId: components["parameters"]["RelayCaseIdPath"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RelayCaseActionRequest"];
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relay/cases/{caseId}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete a relay case. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    caseId: components["parameters"]["RelayCaseIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relay/cases/{caseId}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim a relay case for the current player. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    caseId: components["parameters"]["RelayCaseIdPath"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RelayCaseActionRequest"];
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relay/cases/{caseId}/request-claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request permission to claim a relay case. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    caseId: components["parameters"]["RelayCaseIdPath"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RelayCaseActionRequest"];
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relay/cases/{caseId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit progress for a relay case. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    caseId: components["parameters"]["RelayCaseIdPath"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RelayCaseActionRequest"];
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relay/cases/{caseId}/designate-target": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Designate the next target player for a relay case. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    caseId: components["parameters"]["RelayCaseIdPath"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RelayCaseActionRequest"];
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relay/cases/{caseId}/handoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hand off a relay case to the next player. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    caseId: components["parameters"]["RelayCaseIdPath"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RelayCaseActionRequest"];
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stone-2k/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Stone 2K monitor run data. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rescue-offers/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an active rescue offer for the authenticated user and mode. */
        get: {
            parameters: {
                query: {
                    mode_key: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active rescue offer. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            data?: components["schemas"]["RescueOffer"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rescue-offers/{offerId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept a rescue offer. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    offerId: components["parameters"]["OfferIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rescue-offers/{offerId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a rescue offer. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    offerId: components["parameters"]["OfferIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rescue-offers/{offerId}/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a rescue offer as consumed by the game client. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    offerId: components["parameters"]["OfferIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check administrator permission. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Admin permission state. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            admin?: boolean;
                            super_admin?: boolean;
                            user?: components["schemas"]["User"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read dashboard metrics and recent admin activity. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search and page account users. */
        get: {
            parameters: {
                query?: {
                    q?: string;
                    role?: string;
                    status?: "active" | "inactive";
                    activity?: "7d" | "30d" | "never";
                    sort?: "newest" | "last_active" | "records";
                    page?: components["parameters"]["PageQuery"];
                    limit?: components["parameters"]["LimitQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a unified account, game, achievement, rescue, and audit summary. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AdminUserIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Correct non-authentication profile fields. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AdminUserIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nickname?: string;
                        display_name?: string;
                        avatar_url?: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        trace?: never;
    };
    "/admin/users/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Enable or disable an eligible account. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AdminUserIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        active: boolean;
                    };
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        trace?: never;
    };
    "/admin/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change an eligible account between player and board administrator. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AdminUserIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        role: "player" | "board_admin";
                    };
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        trace?: never;
    };
    "/admin/users/{id}/revoke-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke all existing authentication tokens for a user without changing the password. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AdminUserIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a secure password reset code to the account email. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AdminUserIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/record-import/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify one terminal replay and report trusted derived fields without writing. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AdminUserIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminRecordImportRequest"];
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/record-import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Write one verified replay as an official administrator-imported record. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AdminUserIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminRecordImportRequest"];
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search and page game records across users. */
        get: {
            parameters: {
                query?: {
                    user_id?: number;
                    mode_key?: string;
                    status?: string;
                    record_id?: string;
                    from?: string;
                    to?: string;
                    page?: components["parameters"]["PageQuery"];
                    limit?: components["parameters"]["LimitQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/records/{id}/hide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hide a verified record and rebuild the affected leaderboard. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AdminRecordIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminReasonRequest"];
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/records/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore a hidden record and rebuild the affected leaderboard. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AdminRecordIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminReasonRequest"];
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search administrator audit logs. */
        get: {
            parameters: {
                query?: {
                    actor?: number;
                    target?: number;
                    action?: string;
                    target_type?: string;
                    from?: string;
                    to?: string;
                    page?: components["parameters"]["PageQuery"];
                    limit?: components["parameters"]["LimitQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search game and runtime audit events. */
        get: {
            parameters: {
                query?: {
                    severity?: "debug" | "info" | "warning" | "error" | "critical";
                    user_id?: number;
                    from?: string;
                    to?: string;
                    page?: components["parameters"]["PageQuery"];
                    limit?: components["parameters"]["LimitQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/super-admins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Next console super administrators. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        put?: never;
        /** Grant super administrator access as the root administrator. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        user_id: number;
                    };
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/super-admins/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke super administrator access as the root administrator. */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["AdminUserIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List inspectable database tables. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/table/{tableName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read rows from an admin-visible table. */
        get: {
            parameters: {
                query?: {
                    page?: components["parameters"]["PageQuery"];
                    limit?: components["parameters"]["LimitQuery"];
                };
                header?: never;
                path: {
                    tableName: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute an admin SQL query. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        sql: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/rescue-offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List rescue offers. */
        get: {
            parameters: {
                query?: {
                    user_id?: number;
                    status?: "pending" | "accepted" | "rejected" | "consumed" | "expired";
                    from?: string;
                    to?: string;
                    limit?: components["parameters"]["LimitQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rescue offer list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            data?: components["schemas"]["RescueOffer"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a rescue offer for a user. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminRescueOfferCreateRequest"];
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/rescue-offers/from-replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a rescue offer by parsing a replay string. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        target_user: string;
                        mode_key: string;
                        replay_string: string;
                        expires_in_hours?: number;
                        reason?: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List public achievement definitions. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Achievement catalog. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            data?: components["schemas"]["Achievement"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List achievements earned by the authenticated user. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User achievements. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            data?: components["schemas"]["UserAchievement"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{userId}/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List public achievements earned by a user. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: components["parameters"]["UserIdPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Public user achievements. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            data?: components["schemas"]["UserAchievement"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me/achievement-showcase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the authenticated user's showcase achievements. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Showcase achievements. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            data?: components["schemas"]["AchievementShowcase"];
                        };
                    };
                };
            };
        };
        /** Set up to three showcase achievements. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AchievementShowcaseUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated showcase achievements. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            data?: components["schemas"]["AchievementShowcase"];
                        };
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me/achievement-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a known client achievement event for the authenticated user. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AchievementEventRequest"];
                };
            };
            responses: {
                /** @description Granted or existing achievement for the event. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            data?: components["schemas"]["UserAchievement"];
                            /** @description True only when the event unlocked this achievement during this request. */
                            newly_granted?: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List achievement definitions for super administrators. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Admin achievement catalog. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            data?: components["schemas"]["Achievement"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Create an achievement definition.
         * @description Requires super administrator permission.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AchievementCreateRequest"];
                };
            };
            responses: {
                200: components["responses"]["AchievementResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/achievements/{achievementId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update an achievement definition.
         * @description Requires super administrator permission.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    achievementId: components["parameters"]["AchievementIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AchievementUpdateRequest"];
                };
            };
            responses: {
                200: components["responses"]["AchievementResponse"];
            };
        };
        trace?: never;
    };
    "/admin/achievements/{achievementId}/icon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload an achievement icon.
         * @description Requires super administrator permission.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    achievementId: components["parameters"]["AchievementIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        icon: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["AchievementResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/achievements/{achievementId}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace achievement unlock rules.
         * @description Requires super administrator permission.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    achievementId: components["parameters"]["AchievementIdPath"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        rules: components["schemas"]["AchievementRule"][];
                    };
                };
            };
            responses: {
                200: components["responses"]["AchievementResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/achievements/grant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manually grant an achievement to a user.
         * @description Requires super administrator permission.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AchievementGrantRequest"];
                };
            };
            responses: {
                /** @description Granted user achievement. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiEnvelope"] & {
                            data?: components["schemas"]["UserAchievement"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/achievements/backfill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recalculate achievements from existing verified records.
         * @description Requires super administrator permission and must be idempotent.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        user_id?: number;
                        achievement_id?: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["ApiEnvelopeResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiEnvelope: {
            success?: boolean;
            error?: string;
            code?: string;
            message?: string;
        } & {
            [key: string]: unknown;
        };
        AdminReasonRequest: {
            reason: string;
        };
        AdminRecordImportRequest: {
            replay_string: string;
            mode_key?: string;
            client_record_id?: string;
            /** Format: date-time */
            ended_at?: string;
            reason: string;
        };
        User: {
            id?: number;
            user_id?: number;
            nickname?: string;
            /** Format: email */
            email?: string;
            /** Format: date-time */
            created_at?: string;
            admin?: boolean;
            super_admin?: boolean;
        } & {
            [key: string]: unknown;
        };
        RegisterRequest: {
            nickname: string;
            /** Format: email */
            email?: string;
            password: string;
        } & {
            [key: string]: unknown;
        };
        RegisterStartRequest: {
            nickname: string;
            /** Format: email */
            email: string;
            password: string;
        };
        RegisterVerifyRequest: {
            nickname: string;
            /** Format: email */
            email: string;
            password: string;
            code: string;
        };
        LoginRequest: {
            nickname?: string;
            /** Format: email */
            email?: string;
            password: string;
            /** @enum {string} */
            client?: "web";
            captcha?: string;
        } & {
            [key: string]: unknown;
        };
        PasswordChangeRequest: {
            old_password: string;
            new_password: string;
        };
        LeaderboardEntry: {
            rank?: number;
            user_id?: number;
            nickname?: string;
            score?: number;
            duration_ms?: number;
            speed_ms?: number;
            mode?: string;
            mode_key?: string;
            /** Format: date-time */
            updated_at?: string;
        } & {
            [key: string]: unknown;
        };
        LeaderboardShowcaseEntry: {
            rank: number;
            user_id: number;
            nickname: string;
            score: number;
            max_tile: number;
            board_sum: number;
            duration_ms: number;
            /** Format: date-time */
            game_date?: string | null;
            /** Format: date-time */
            uploaded_at?: string | null;
        };
        LeaderboardShowcaseSummary: {
            total_records: number;
            total_players: number;
            reached_16384: number;
            reached_32768: number;
        };
        LeaderboardShowcaseTrendPoint: {
            /** Format: date */
            date: string;
            best_score: number;
        };
        LeaderboardAchievementFocus: {
            completed_all: boolean;
            achievement_id?: string;
            name?: string;
            current?: number;
            target?: number;
            progress_percent?: number;
        };
        UserRecordStats: {
            summary?: {
                [key: string]: unknown;
            };
            by_mode?: {
                [key: string]: unknown;
            }[];
            rating?: {
                value: number | null;
                /** @enum {string} */
                status: "insufficient_data";
            };
            tile_milestones?: {
                [key: string]: unknown;
            }[];
            speedruns?: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        ScoreSubmitRequest: {
            score: number;
            mode?: string;
            mode_key?: string;
        } & {
            [key: string]: unknown;
        };
        GameRecord: {
            id?: string;
            user_id?: number;
            nickname?: string;
            score?: number;
            board_sum?: number;
            duration_ms?: number;
            mode?: string;
            mode_key?: string;
            mode_bucket?: string;
            /** @enum {string} */
            record_era?: "beta" | "official_v1";
            max_tile?: number;
            replay?: string;
            replay_url?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /** Format: date-time */
            deleted_at?: string;
        } & {
            [key: string]: unknown;
        };
        GameRecordSubmitRequest: {
            /** @enum {integer} */
            record_schema_version?: 1;
            client_record_id?: string;
            score: number;
            duration_ms?: number;
            mode?: string;
            mode_key: string;
            mode_bucket?: string;
            max_tile?: number;
            replay?: string;
            replay_string?: string;
            session_replay_v1?: {
                [key: string]: unknown;
            };
            ranked_session_token?: string;
            challenge_id?: string;
            rescue_id?: string;
            admin_rescue?: boolean;
        } & {
            [key: string]: unknown;
        };
        RankedSessionStartRequest: {
            /** @enum {integer} */
            attempt_schema_version?: 1;
            mode_key: string;
            mode?: string;
            mode_bucket?: string;
            board_width?: number;
            board_height?: number;
            ruleset?: string;
        } & {
            [key: string]: unknown;
        };
        RankedSessionAttemptRequest: {
            /** @enum {string} */
            event: "begin" | "abandon";
            mode_key: string;
            ranked_session_token: string;
            replay_string: string;
            /**
             * @description Required for abandon and omitted for begin.
             * @enum {string}
             */
            reason?: "restart" | "navigation";
            /** @enum {integer} */
            attempt_schema_version: 1;
        };
        RankedSession: {
            id?: string;
            challenge_id?: string;
            seed?: string;
            ranked_session_token?: string;
            mode_key?: string;
            /** @enum {string} */
            status?: "created" | "started" | "consumed" | "abandoned" | "expired";
            /** @enum {string} */
            record_era?: "beta" | "official_v1";
            /** Format: date-time */
            issued_at?: string;
        } & {
            [key: string]: unknown;
        };
        RankedCheckpoint: {
            mode_key: string;
            board?: number[][];
            score?: number;
            duration_ms?: number;
            state?: {
                [key: string]: unknown;
            };
            ranked_session_token?: string;
            /** Format: date-time */
            updated_at?: string;
        } & {
            [key: string]: unknown;
        };
        RescueOffer: {
            id?: string;
            user_id?: number;
            target_nickname?: string;
            mode_key?: string;
            mode_bucket?: string;
            board?: number[][];
            score?: number;
            duration_ms?: number;
            status?: string;
            game_progress_status?: string;
            reason?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            expires_at?: string;
        } & {
            [key: string]: unknown;
        };
        AdminRescueOfferCreateRequest: {
            user_id: number;
            mode_key: string;
            mode_bucket: string;
            board: number[][];
            score: number;
            duration_ms: number;
            expires_in_hours?: number;
            reason?: string;
        };
        RelayCase: {
            id?: string;
            case_id?: string;
            board?: number[][];
            board_size?: string;
            status?: string;
            current_user_id?: number;
            current_nickname?: string;
            target_user_id?: number;
            target_nickname?: string;
            score?: number;
            duration_ms?: number;
            replay?: string;
            replay_string?: string;
            /** Format: date-time */
            updated_at?: string;
        } & {
            [key: string]: unknown;
        };
        RelayCaseActionRequest: {
            user_id?: number;
            nickname?: string;
            target_user_id?: number;
            target_nickname?: string;
            board?: number[][];
            score?: number;
            duration_ms?: number;
            replay?: string;
            replay_string?: string;
            payload?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        Achievement: {
            id: string;
            series_id?: string;
            level?: number;
            name: string;
            description: string;
            name_i18n?: components["schemas"]["LocalizedText"];
            description_i18n?: components["schemas"]["LocalizedText"];
            icon_url: string;
            /** @enum {string} */
            status: "draft" | "active" | "archived";
            sort_order?: number;
            rules?: components["schemas"]["AchievementRule"][];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        AchievementRule: {
            /** @enum {string} */
            type: "max_tile_reached" | "nth_max_tile_reached" | "max_tile_within_duration" | "event_rank" | "manual_grant";
            params: {
                tile?: number;
                count?: number;
                duration_ms?: number;
                mode_key?: string;
                event_id?: string;
                rank?: number;
            } & {
                [key: string]: unknown;
            };
        };
        LocalizedText: {
            [key: string]: string;
        };
        UserAchievement: {
            achievement: components["schemas"]["Achievement"];
            /** Format: date-time */
            earned_at: string;
            /** @enum {string} */
            source?: "record" | "event" | "manual" | "backfill";
            record_id?: string;
            event_id?: string;
        };
        AchievementShowcase: {
            achievements: components["schemas"]["UserAchievement"][];
        };
        AchievementShowcaseUpdateRequest: {
            achievement_ids: string[];
        };
        AchievementEventRequest: {
            /** @enum {string} */
            event_id: "breakout_easter_egg_discovered" | "lost_page_visited";
        };
        AchievementCreateRequest: {
            series_id?: string;
            /** @default 1 */
            level: number;
            name: string;
            description: string;
            name_i18n?: components["schemas"]["LocalizedText"];
            description_i18n?: components["schemas"]["LocalizedText"];
            icon_url?: string;
            /**
             * @default draft
             * @enum {string}
             */
            status: "draft" | "active" | "archived";
            sort_order?: number;
            rules?: components["schemas"]["AchievementRule"][];
        };
        AchievementUpdateRequest: {
            series_id?: string;
            level?: number;
            name?: string;
            description?: string;
            name_i18n?: components["schemas"]["LocalizedText"];
            description_i18n?: components["schemas"]["LocalizedText"];
            icon_url?: string;
            /** @enum {string} */
            status?: "draft" | "active" | "archived";
            sort_order?: number;
            rules?: components["schemas"]["AchievementRule"][];
        };
        AchievementGrantRequest: {
            user_id: number;
            achievement_id: string;
            /**
             * @default manual
             * @enum {string}
             */
            source: "manual" | "event" | "backfill";
            record_id?: string;
            event_id?: string;
            note?: string;
        };
    };
    responses: {
        /** @description Generic API envelope. */
        ApiEnvelopeResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiEnvelope"];
            };
        };
        /** @description Authenticated user and token. */
        AuthResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiEnvelope"] & {
                    token?: string;
                    user?: components["schemas"]["User"];
                    /** @description One-time achievement unlocks to show after this authentication response. */
                    achievements?: components["schemas"]["UserAchievement"][];
                };
            };
        };
        /** @description User profile result. */
        UserResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiEnvelope"] & {
                    user?: components["schemas"]["User"];
                    data?: components["schemas"]["User"];
                };
            };
        };
        /** @description Achievement definition result. */
        AchievementResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiEnvelope"] & {
                    data?: components["schemas"]["Achievement"];
                };
            };
        };
    };
    parameters: {
        AdminUserIdPath: number;
        AdminRecordIdPath: string;
        UserIdPath: number;
        RecordIdPath: string;
        OfferIdPath: string;
        AchievementIdPath: string;
        RelayCaseIdPath: string;
        PageQuery: number;
        LimitQuery: number;
        NicknameQuery: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
